(self.AMP=self.AMP||[]).push({n:"amp-position-observer",v:"2008290323001",f:(function(AMP,_){
'use strict';var l="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function m(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}m(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={a:!0},r={};try{r.__proto__=q;p=r.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n;function u(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var aa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var v=self.AMP_CONFIG||{},ba=("string"==typeof v.cdnProxyRegex?new RegExp(v.cdnProxyRegex):v.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function w(a){if(self.document&&self.document.head&&(!self.location||!ba.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}v.cdnUrl||w("runtime-host");v.geoApiUrl||w("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var x=self.__AMP_LOG;function y(){if(!x.user)throw Error("failed to call initLogConstructor");return x.user}function z(){if(x.dev)return x.dev;throw Error("failed to call initLogConstructor");}function A(a,b,c){return y().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function B(a){return a||{}};B({c:!0,v:!0,a:!0,ad:!0});function ca(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(f){z().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function da(a){var b=a.ownerDocument.defaultView,c=b.__AMP_TOP||(b.__AMP_TOP=b),d=b!=c;if(c.__AMP__EXPERIMENT_TOGGLES)var f=c.__AMP__EXPERIMENT_TOGGLES;else{c.__AMP__EXPERIMENT_TOGGLES=Object.create(null);f=c.__AMP__EXPERIMENT_TOGGLES;if(c.AMP_CONFIG)for(var g in c.AMP_CONFIG){var e=c.AMP_CONFIG[g];"number"===typeof e&&0<=e&&1>=e&&(f[g]=Math.random()<e)}if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-doc-opt-in"])&&0<c.AMP_CONFIG["allow-doc-opt-in"].length&&(g=c.AMP_CONFIG["allow-doc-opt-in"],
e=c.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=e.getAttribute("content").split(",");for(var h=0;h<e.length;h++)-1!=g.indexOf(e[h])&&(f[e[h]]=!0)}Object.assign(f,ca(c));if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-url-opt-in"])&&0<c.AMP_CONFIG["allow-url-opt-in"].length){g=c.AMP_CONFIG["allow-url-opt-in"];e=c.location.originalHash||c.location.hash;c=Object.create(null);if(e)for(var k;k=aa.exec(e);)h=u(k[1],k[1]),k=k[2]?u(k[2].replace(/\+/g," "),k[2]):"",c[h]=k;for(e=
0;e<g.length;e++)h=c["e-"+g[e]],"1"==h&&(f[g[e]]=!0),"0"==h&&(f[g[e]]=!1)}}var ea=!!f["ampdoc-fie"];d&&!ea?a=C(b,"action")?D(b,"action"):null:(a=E(a),a=F(a),a=C(a,"action")?D(a,"action"):null);return a}function fa(a){var b=G,c=E(a),d=F(c),f=H(d),g=f["position-observer"];g||(g=f["position-observer"]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});g.ctor||g.obj||(g.ctor=b,g.context=c,g.resolve&&D(d,"position-observer"))}
function I(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return D(a,b)}function J(a,b){var c=E(a);c=F(c);return D(c,b)}function E(a){return a.nodeType?I((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a){a=E(a);return a.isSingleDoc()?a.win:a}function D(a,b){C(a,b);a=H(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function H(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function C(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function K(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function L(a,b){return a.top<b.top?"top":a.bottom>b.bottom?"bottom":"inside"}function M(a,b){return a&&b?a.left==b.left&&a.top==b.top&&a.width==b.width&&a.height==b.height:!1};function N(a,b,c,d){this.element=b;this.P=d;this.fidelity=c;this.turn=0==c?Math.floor(4*Math.random()):0;this.B=null;this.j=J(a,"viewport")}
N.prototype.update=function(a){var b=this;if(!a){if(0!=this.turn){this.turn--;return}0==this.fidelity&&(this.turn=4)}var c=this.j.getSize(),d=K(0,0,c.width,c.height);this.j.getClientRectAsync(this.element).then(function(a){var c={positionRect:a,viewportRect:d,relativePos:null},e=b.B;if(!(e&&M(e.positionRect,c.positionRect)&&M(e.viewportRect,c.viewportRect))){e=c.positionRect;c.relativePos=L(e,c.viewportRect);var f=c.viewportRect;e.top<=f.bottom&&f.top<=e.bottom&&e.left<=f.right&&f.left<=e.right?(b.B=
c,b.P(c)):b.B&&(b.B=null,c.positionRect=null,b.P(c))}})};function O(a){A(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|cm|mm|q|in|pc|pt)$/.test(a),"Invalid length value: %s",a);return a};function P(a,b,c){var d={detail:c};Object.assign(d,void 0);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,d);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!d.bubbles,!!d.cancelable,c);return a};function ha(a,b){function c(){d=0;var e=500-(a.Date.now()-f);if(0<e)d=a.setTimeout(c,e);else{var h=g;g=null;b.apply(null,h)}}var d=0,f=0,g=null;return function(b){for(var e=[],k=0;k<arguments.length;++k)e[k-0]=arguments[k];f=a.Date.now();g=e;d||(d=a.setTimeout(c,500))}};function G(a){var b=this;this.V=a;this.U=a.win;this.h=[];this.Z=I(this.U,"vsync");this.j=J(a,"viewport");this.H=[];this.K=this.M=this.L=!1;this.W=ha(this.U,function(){b.L=!1})}G.prototype.observe=function(a,b,c){var d=this,f=new N(this.V,a,b,c);this.h.push(f);this.K||ia(this);f.update();return function(){for(var a=0;a<d.h.length;a++)if(d.h[a]==f){d.h.splice(a,1);0==d.h.length&&Q(d);break}}};
G.prototype.unobserve=function(a){for(var b=0;b<this.h.length;b++)if(this.h[b].element==a){this.h.splice(b,1);0==this.h.length&&Q(this);return}z().error("POSITION_OBSERVER","cannot unobserve unobserved element")};function ia(a){a.K=!0;a.H.push(a.j.onScroll(function(){a.W();a.L=!0;a.M||R(a)}));a.H.push(a.j.onResize(function(){a.updateAllEntries(!0)}))}function Q(a){for(a.K=!1;a.H.length;)a.H.pop()()}G.prototype.updateAllEntries=function(a){for(var b=0;b<this.h.length;b++)this.h[b].update(a)};
function R(a){a.updateAllEntries();a.M=!0;a.L?a.Z.measure(function(){R(a)}):a.M=!1};function S(a){a=AMP.BaseElement.call(this,a)||this;a.w=null;a.m=null;a.j=null;a.l=!1;a.G=0;a.o=0;a.N="0";a.J="0";a.C=0;a.S=0;a.I=null;a.F=null;a.A=null;a.D=0;a.R=0;a.T=!1;a.O=!1;return a}var T=AMP.BaseElement;S.prototype=l(T.prototype);S.prototype.constructor=S;if(t)t(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(T,U);V&&Object.defineProperty(S,U,V)}else S[U]=T[U];S.aa=T.prototype;
S.prototype.buildCallback=function(){this.getAmpDoc().whenFirstVisible().then(this.X.bind(this));this.T=this.element.hasAttribute("once")};S.prototype.X=function(){var a=this;ja(this);this.w=da(this.element);this.j=J(this.element,"viewport");this.m||(fa(this.getAmpDoc()),this.m=J(this.element,"position-observer"));this.getAmpDoc().whenReady().then(function(){var b=W(a);a.m.observe(b,1,a.Y.bind(a))})};
function X(a){var b=a.j.getScrollTop(),c=B({"start-scroll-offset":b,"end-scroll-offset":b+a.R,"initial-inview-percent":a.D}),d=P(a.win,"amp-position-observer.scroll",B({percent:a.D,positionObserverData:c}));a.w.trigger(a.element,"scroll",d,1)}
S.prototype.Y=function(a){if(!this.T||!this.O){var b=this.l,c=this.I&&this.I.height;this.A||(this.A=a.viewportRect.height);var d=this.A-a.viewportRect.height,f=0;150>Math.abs(d)?f=d:this.A=null;a.viewportRect=K(a.viewportRect.left,a.viewportRect.top,a.viewportRect.width,a.viewportRect.height+f);this.I=a.viewportRect;c!=a.viewportRect.height&&(this.C=Y(this,this.N),this.S=Y(this,this.J));d=a.viewportRect;d=K(d.left,d.top+this.C,d.width,d.height-this.S-this.C);f=a.positionRect;var g;if(f){var e=g=L(f,
d);if("inside"==e)this.l=!0;else{var h=f.height*("top"==e?this.G:this.o);this.l="bottom"==e?f.top<=d.bottom-h:f.bottom>=d.top+h}}else this.l=!1,g=a.relativePos;b&&!this.l&&(this.D="bottom"==g?0:1,X(this),e=P(this.win,"amp-position-observer.exit",B({})),this.w.trigger(this.element,"exit",e,1),this.O=!0);!b&&this.l&&(e=P(this.win,"amp-position-observer.enter",B({})),this.w.trigger(this.element,"enter",e,1));this.l&&(f&&(e=d.height+f.height-(f.height*this.o+f.height*this.G),d=Math.abs(f.top-this.C-(d.height-
f.height*this.o)),this.D=d/e,this.R=e-d),X(this))}};function ja(a){var b=a.element.getAttribute("intersection-ratios");if(b){var c=b.trim().split(" ");a.G=Z(c[0]);a.o=a.G;c[1]&&(a.o=Z(c[1]))}var d=a.element.getAttribute("viewport-margins");d&&(d=d.trim().split(" "),a.N=d[0],a.J=a.N,d[1]&&(a.J=d[1]));a.F=a.element.getAttribute("target")}
function W(a){var b=a.F?y().assertElement(a.win.document.getElementById(a.F),"No element found with id:"+a.F):a.element.parentNode;a.win.document.body===b&&(b=a.win.document.documentElement);return b}
function Y(a,b){b="number"==typeof b?b+"px":b&&/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|cm|mm|q|in|pc|pt)?$/.test(b)?/^\d+(\.\d+)?$/.test(b)?b+"px":b:void 0;b=O(b);var c=b;O(c);c=A(/[a-z]+/i.exec(c),"Failed to read units from %s",c)[0];var d=parseFloat(b);d="number"===typeof d&&isFinite(d)?d:void 0;if(!d)return 0;A("px"==c||"vh"==c,"Only pixel or vh are valid as units for exclusion margins: "+b);"vh"==c&&(d=d/100*a.I.height);return d}
function Z(a){var b=parseFloat(a);A(0<=b&&1>=b,"Ratios must be a decimal between 0 and 1: "+a);return b}S.prototype.$=function(){if(this.m){var a=W(this);this.m.unobserve(a);this.m=null}};(function(a){a.registerElement("amp-position-observer",S)})(self.AMP);
})});

//# sourceMappingURL=amp-position-observer-0.1.js.map
